linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - unused
    - style
  disable:
    - paralleltest
    - wrapcheck
    - whitespace
    - wsl
    - godot
    - lll
    - funlen
    - gofumpt
    - unparam
    - tagliatelle
    - forbidigo
    - gci
    - varnamelen
    - exhaustruct
    - depguard
    - nolintlint
    - mnd
    - copyloopvar
    - revive
    - gocognit
    - nestif
    - stylecheck
    - godox
    - cyclop
    - nonamedreturns
    - ireturn
    - noctx
    - containedctx
    - err113
run:
  tests: false
issues:
  fix: false
    